# Common Labels
labels:
  app: "egov-otp"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "otp"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_otp_schema"
    image:
      repository: "egov-otp-db"
      tag: v2.9.2-4a60f20

# Container Configs
image:
  repository: "egov-otp"
  tag: v2.9.2-4a60f20
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/otp/health"
  readinessProbePath: "/otp/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"    
